# NumPy Arrays

In [2]:
my_list=[1,2,3]

In [1]:
import numpy as np

In [4]:
np.array(my_list)

array([1, 2, 3])

In [2]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Exercise Numpy

In [3]:
np.zeros(10) # create 0 10 times

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10) #create 1 10times

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.ones(10)*5 #create 5 10times

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [9]:
np.arange(10,51) # create array range from 10 to 50

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [10]:
np.arange(10,51,2) #create array range from 10 to 50 but even number

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [11]:
np.arange(9).reshape(3,3) # create array 3D from num range from 0 to 8

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

a=np.arange(9)
a.reshape(3,3)

In [14]:
np.eye(3) #create a 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.random.rand(1) #create generate a random number between 0 and 1

array([0.57227245])

In [21]:
np.random.randn(25) # create generate array of 25 random numbers sampled from a standard normal distribution

array([ 1.04627909,  1.09090977, -0.48025917,  0.27657239, -0.36645319,
        0.96825494, -0.81325039, -1.32633219, -1.80617357,  1.06480005,
       -2.07220947, -0.47337298,  0.50486068,  0.58073312,  0.08018788,
       -0.54546716, -0.30483313, -0.81059571,  0.74954906,  0.3882952 ,
       -0.08500331,  0.48107045, -1.40512618, -1.32402821,  0.30108056])

In [28]:
np.arange(1,101).reshape(10,10)/100 # create array from 0.01 to 1

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [30]:
np.linspace(0,1,20) # create an array of 20 linearly spaced points between 0 and 1

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [89]:
mat=np.arange(1,26).reshape(5,5) # create 5D range in (1,26)

In [90]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [91]:
mat[2,:] #Grab row all row 2

array([11, 12, 13, 14, 15])

In [92]:
mat[3,4] # grab 20 in mat

20

In [93]:
mat[3][4] # grab 20 in mat

20

In [108]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [109]:
mat[:3,1]

array([ 2,  7, 12])

In [95]:
mat[-1,:] # grab the last column in array

array([21, 22, 23, 24, 25])

In [96]:
mat[-2:,:] # grab last 2 column in array

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [97]:
mat.sum() # sum of mat

325

In [98]:
np.std(mat) # create standard deviation of the values in mat

7.211102550927978

In [99]:
sum(mat) # sum colunm in array

array([55, 60, 65, 70, 75])

In [100]:
mat.sum(axis=0) #same

array([55, 60, 65, 70, 75])